### PR TITLE
Add ilwoo Changes 

### PR DESCRIPTION
**Pull request by mmmosman88**

### CODE REVIEW

**Comment by juanprietob** [comment]
These conflicts need to be resolved. Use the Slicer development style naming of variables and commit messages.

**Comment by jcfr** [comment]
@juanprietob Which repository should be considered the upstream one ? 

Considering that (1) issue tracker for this repository is not available  and (2) most of the activity is happening at https://github.com/ilwoolyu/MeshLib , I suggest that we make an effort not to diverge from the upstream repository.

Here is the proposal:

* step 1: Push force master of this fork to match https://github.com/ilwoolyu/MeshLib  master branch

* step 2: if still needed, contribute #4 to https://github.com/ilwoolyu/MeshLib

Moving forward, if there are changes that have been contributed upstream (or in the process of being contributed), the approach will be to create branches specific to the `NIRALUser/MeshLib` repository.
For more details, see [Naming convention for Slicer fork branches](https://www.slicer.org/wiki/Documentation/Nightly/Developers/ProjectForks#Naming_convention_for_Slicer_fork_branches) for more details

That said, if you want to keep a reference to the current master so that existing project can still built, the current master would be renamed `niraluser-0.0.0-20161011-477e4baf0`



> These conflicts need to be resolved. Use the Slicer development style naming of variables and commit messages.

Considering that the commit proposed by @mmmosman88 were cherry-picked from upstream, I suggest they remain as they are. 


Cc: @bpaniagua @phcerdan @vicory

**Comment by jcfr** [comment]
To reduce confusion, an other alternative is to transfer the ownership of the original repo to the NIRALUser organization.

Same remarks applies to https://github.com/NIRALUser/SurfRemesh

**Comment by vicory** [comment]
I agree that it would be nice to have all of these issues solved, but from the point of view of SALT is there a reason this needs to be done now instead of just pulling in the version of the code/extension that has already been tested for the release and then work on including upstream changes later?

**Comment by jcfr** [comment]
Both will happen in parallel, just wanted to raise this earlier than later.

We already have branches specific to salt, and will be done shortly with
the integration to get our release ready.

Jc

**Comment by juanprietob** [comment]
The upstream should be the NIRALUser repository. I will integrate the changes by Ilwoo.

**Comment by juanprietob** [comment]
I kept the changes made by Ilwoo into the repository

**Comment by jcfr** [comment]
> The upstream should be the NIRALUser repository. I will integrate the changes by Ilwoo.

Great.

@ilwoolyu  To void confusion, you could delete you repository and then fork again the one from NIRALUser

@juanprietob Could you enable the issue tracker in this repo ?

image

**Comment by phcerdan** [comment]
This repo still shows it is out-of-sync from ilwooluy: screenshot from 2018-08-20 11-36-43

**Comment by juanprietob** [comment]
The issue tracker has been enabled. 
@ilwoolyu could you please integrate the chances from the NIRAL repo or fork again the repository?

**Pull request merged**
